"use client";

import { useState } from "react";
import { Check, ClipboardCheck, FileSearch, LoaderCircle, MessageSquareWarning, Quote, RotateCcw, ShieldAlert, X } from "lucide-react";
import { apiRequest, arrayValue, citationDisplay, citationRecords, firstString, formatDate, idOf, recordValue, type ApiRecord } from "@/components/api";
import { useApi } from "@/components/hooks/use-api";
import { Badge, EmptyState, ErrorState, LoadingState, SeedLabel, statusTone, textAreaClass } from "@/components/ui";
import type { AppRole } from "@/lib/auth/roles";

type Decision = "approved" | "rejected" | "revision_requested";

export function ApprovalQueue({ role }: { role: AppRole }) {
  const { data, loading, error, refresh } = useApi("/api/v1/approvals");
  const approvals = arrayValue<ApiRecord>(data, ["approvals", "requests"]);
  const [selectedId, setSelectedId] = useState("");
  const selectedSummary = approvals.find((item) => idOf(item) === selectedId) ?? approvals[0];
  const details = useApi(selectedSummary ? `/api/v1/approvals/${encodeURIComponent(idOf(selectedSummary))}` : null);
  const detailRecord = recordValue(details.data);
  const selected = Object.keys(detailRecord).length ? detailRecord : selectedSummary;
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState("");
  const canDecide = role === "administrator" || role === "policy_manager";
  if (loading && !data) return <div className="rounded-2xl border bg-white"><LoadingState label="Loading approval queue…" rows={7} /></div>;
  if (error && !data) return <div className="rounded-2xl border bg-white"><ErrorState message={error} onRetry={refresh} /></div>;
  if (!approvals.length) return <div className="rounded-2xl border bg-white"><EmptyState icon={ClipboardCheck} title="The approval queue is clear" description="High and critical findings appear here when a workflow pauses for human judgment." /></div>;

  async function decide(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected || !canDecide) return;
    const submitter = (event.nativeEvent as SubmitEvent).submitter;
    const form = new FormData(event.currentTarget, submitter); const decision = String(form.get("decision")) as Decision; const notes = String(form.get("notes") ?? "").trim();
    if ((decision === "rejected" || decision === "revision_requested") && !notes) return setMessage("Add reviewer notes for a rejection or revision request.");
    setSubmitting(true); setMessage("");
    try { await apiRequest(`/api/v1/approvals/${encodeURIComponent(idOf(selected))}/decisions`, { method: "POST", body: JSON.stringify({ decision, notes, expectedAnalysisVersion: Number(selected.analysis_version) }) }); setMessage("Decision recorded in the audit trail."); refresh(); }
    catch (caught) { setMessage(caught instanceof Error ? caught.message : "The decision could not be recorded."); } finally { setSubmitting(false); }
  }

  const comparison = selected ? recordValue(selected, ["policy_comparisons"]) : {};
  const findings = [...arrayValue<ApiRecord>(comparison.risk_assessments), ...arrayValue<ApiRecord>(comparison.policy_conflicts), ...arrayValue<ApiRecord>(comparison.policy_changes)];
  const actionPlans = arrayValue<ApiRecord>(comparison.action_plans);
  const citations = findings.flatMap(citationRecords);
  return <div className="grid gap-6 xl:grid-cols-[360px_1fr]">
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b px-5 py-4"><h2 className="text-sm font-semibold">Requests</h2><p className="mt-1 text-xs text-[#7a8580]">{approvals.length} visible to your reviewer role</p></div><div className="divide-y divide-[#edf0ee]">{approvals.map((item) => { const itemId = idOf(item); const severity = firstString(item, ["risk_level", "severity"], "High"); const active = itemId === idOf(selected ?? {}); return <button key={itemId} type="button" onClick={() => { setSelectedId(itemId); setMessage(""); }} className={`w-full p-4 text-left transition ${active ? "bg-[#edf5f1]" : "hover:bg-[#fafbf9]"}`}><div className="flex items-start justify-between gap-2"><span className={`grid size-9 place-items-center rounded-xl ${severity.toLowerCase() === "critical" ? "bg-rose-100 text-rose-700" : "bg-amber-100 text-amber-700"}`}><ShieldAlert className="size-4" /></span><Badge tone={statusTone(severity)}>{severity}</Badge></div><div className="mt-3 flex flex-wrap items-center gap-2"><p className="line-clamp-2 text-xs font-semibold leading-5">{firstString(item, ["title", "summary"], "High-risk policy finding")}</p><SeedLabel seed={item.is_seed === true} /></div><p className="mt-2 text-[10px] text-[#7d8882]">Requested {formatDate(item.created_at, true)}</p></button>; })}</div></section>
    {selected && <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#0d684d]">Approval review</p><h2 className="mt-2 text-lg font-semibold">{firstString(selected, ["title", "summary"], "High-risk policy finding")}</h2></div><Badge tone={statusTone(firstString(selected, ["status"], "pending"))}>{firstString(selected, ["status"], "pending").replaceAll("_", " ")}</Badge></div><p className="mt-4 text-sm leading-6 text-[#65726c]">{firstString(selected, ["description", "rationale", "explanation"], "Inspect the cited findings and proposed actions before recording a decision.")}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#f7f9f7] p-3"><p className="text-[10px] text-[#7c8782]">Analysis version</p><p className="mt-1 text-xs font-semibold">{firstString(selected, ["analysis_version"], "1")}</p></div><div className="rounded-xl bg-[#f7f9f7] p-3"><p className="text-[10px] text-[#7c8782]">Risk level</p><p className="mt-1 text-xs font-semibold capitalize">{firstString(selected, ["risk_level", "severity"], "High")}</p></div><div className="rounded-xl bg-[#f7f9f7] p-3"><p className="text-[10px] text-[#7c8782]">Workflow</p><p className="mt-1 truncate text-xs font-semibold">{firstString(selected, ["workflow_run_id", "run_id"], "Checkpointed")}</p></div></div></div>
      <div className="space-y-5 p-5 sm:p-6">
        {findings.length > 0 && <div><h3 className="flex items-center gap-2 text-xs font-semibold"><FileSearch className="size-4 text-[#0d684d]" />Findings under review</h3><div className="mt-3 space-y-3">{findings.map((finding, index) => <div key={idOf(finding) || index} className="rounded-xl border bg-[#fafbf9] p-4"><div className="flex justify-between gap-3"><p className="text-xs font-semibold">{firstString(finding, ["title", "summary", "change_type"], "Policy finding")}</p><Badge tone={statusTone(firstString(finding, ["risk_level", "severity"], "high"))}>{firstString(finding, ["risk_level", "severity"], "high")}</Badge></div><p className="mt-2 text-xs leading-5 text-[#67746e]">{firstString(finding, ["explanation", "description", "impact"], "No additional explanation was returned.")}</p></div>)}</div></div>}
        {actionPlans.length > 0 && <details className="rounded-xl border"><summary className="flex list-none items-center gap-2 p-4 text-xs font-semibold text-[#0d684d]"><ClipboardCheck className="size-4" />Inspect action plans ({actionPlans.length})</summary><div className="space-y-3 border-t p-4">{actionPlans.map((plan, index) => <div key={idOf(plan) || index} className="rounded-lg bg-[#fafbf9] p-3"><p className="text-xs font-semibold">{firstString(plan, ["title"], "Department action plan")}</p><p className="mt-1 text-[11px] leading-5 text-[#64716b]">{firstString(plan, ["summary", "description"], "Review the assigned implementation items.")}</p>{arrayValue<ApiRecord>(plan.action_items).length > 0 && <ul className="mt-2 list-disc space-y-1 pl-4 text-[11px] text-[#64716b]">{arrayValue<ApiRecord>(plan.action_items).map((item, itemIndex) => <li key={idOf(item) || itemIndex}>{firstString(item, ["title", "description"], "Action item")}</li>)}</ul>}</div>)}</div></details>}
        {citations.length > 0 && <details className="rounded-xl border"><summary className="flex list-none items-center gap-2 p-4 text-xs font-semibold text-[#0d684d]"><Quote className="size-4" />Inspect cited evidence ({citations.length})</summary><div className="space-y-4 border-t p-4">{citations.map((citation, index) => { const display = citationDisplay(citation); return display ? <div key={firstString(citation, ["chunkId", "chunk_id", "id"], String(index))}><p className="text-[11px] font-semibold">{display.documentTitle} · v{display.version}</p><p className="mt-1 text-[10px] text-[#7d8882]">{display.sectionHeading}{display.pageNumber ? ` · Page ${display.pageNumber}` : ""}</p><p className="mt-2 text-xs leading-5 text-[#5f6c66]">{display.evidenceSnippet}</p></div> : null; })}</div></details>}
        {canDecide && firstString(selected, ["status"], "pending") === "pending" ? <form onSubmit={decide} className="rounded-2xl border border-[#dce3df] bg-[#f8faf8] p-4"><label className="text-xs font-semibold text-[#3d4b45]">Reviewer notes<textarea name="notes" rows={4} className={textAreaClass} placeholder="Explain your decision, required correction, or implementation condition…" disabled={submitting} /></label>{message && <p role="status" className={`mt-3 text-xs ${message.includes("recorded") ? "text-emerald-700" : "text-rose-700"}`}>{message}</p>}<div className="mt-4 grid gap-2 sm:grid-cols-3"><button name="decision" value="approved" disabled={submitting} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-3 text-xs font-semibold text-white disabled:opacity-50"><Check className="size-4" />Approve</button><button name="decision" value="revision_requested" disabled={submitting} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-amber-300 bg-amber-50 px-3 text-xs font-semibold text-amber-900 disabled:opacity-50">{submitting ? <LoaderCircle className="size-4 animate-spin" /> : <RotateCcw className="size-4" />}Request revision</button><button name="decision" value="rejected" disabled={submitting} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-rose-300 bg-rose-50 px-3 text-xs font-semibold text-rose-800 disabled:opacity-50"><X className="size-4" />Reject</button></div><p className="mt-3 flex gap-2 text-[10px] leading-4 text-[#7d8882]"><MessageSquareWarning className="size-3.5 shrink-0" />Your identity, notes, timestamp, previous status, new status, and analysis version are written to the audit trail.</p></form> : <div className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-xs leading-5 text-sky-900">{canDecide ? "This approval request is resolved. Its decision controls are now locked." : "You have read-only reviewer access. An Administrator or Policy Manager must record the decision."}</div>}
      </div></section>}
  </div>;
}
