"use client";

import { useState } from "react";
import { Building2, Check, LoaderCircle, MailPlus, Save, Settings2, TriangleAlert, UserCog, Users } from "lucide-react";
import { apiRequest, arrayValue, firstString, formatDate, idOf, recordValue, type ApiRecord } from "@/components/api";
import { useApi } from "@/components/hooks/use-api";
import { Badge, EmptyState, ErrorState, LoadingState, SectionCard, fieldClass, primaryButtonClass, statusTone } from "@/components/ui";

export function UserManagement() {
  const { data, loading, error, refresh } = useApi("/api/v1/users");
  const departmentsQuery = useApi("/api/v1/departments");
  const users = arrayValue<ApiRecord>(data, ["users", "members"]); const departments = arrayValue<ApiRecord>(departmentsQuery.data, ["departments"]);
  const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  async function invite(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setMessage(""); const form = new FormData(event.currentTarget); const departmentId = String(form.get("departmentId") || ""); try { await apiRequest("/api/v1/users", { method: "POST", body: JSON.stringify({ email: String(form.get("email")), fullName: String(form.get("fullName")), role: String(form.get("role")), departmentIds: departmentId ? [departmentId] : [] }) }); setMessage("Invitation created."); event.currentTarget.reset(); refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not invite this user."); } finally { setSubmitting(false); } }
  async function update(event: React.FormEvent<HTMLFormElement>, userId: string) { event.preventDefault(); const form = new FormData(event.currentTarget); const departmentId = String(form.get("departmentId") || ""); setMessage(""); try { await apiRequest(`/api/v1/users/${encodeURIComponent(userId)}/membership`, { method: "PATCH", body: JSON.stringify({ role: String(form.get("role")), status: String(form.get("status")), departmentIds: departmentId ? [departmentId] : [] }) }); setMessage("Membership updated."); refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not update membership."); } }
  if (loading && !data) return <SectionCard><LoadingState label="Loading organization members…" rows={7} /></SectionCard>;
  if (error && !data) return <SectionCard><ErrorState message={error} onRetry={refresh} /></SectionCard>;
  return <div className="space-y-6"><SectionCard title="Invite a member" description="Roles are stored in organization membership records and enforced again at the API and database layers."><form onSubmit={invite} className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-5 sm:p-6"><label className="text-xs font-semibold text-[#415049]">Full name<input name="fullName" className={fieldClass} required placeholder="Avery Morgan" /></label><label className="text-xs font-semibold text-[#415049]">Email<input name="email" type="email" className={fieldClass} required placeholder="avery@college.edu" /></label><label className="text-xs font-semibold text-[#415049]">Role<select name="role" className={fieldClass} defaultValue="department_user"><option value="administrator">Administrator</option><option value="policy_manager">Policy manager</option><option value="department_user">Department user</option><option value="auditor">Auditor</option></select></label><label className="text-xs font-semibold text-[#415049]">Department<select name="departmentId" className={fieldClass} defaultValue=""><option value="">Organization-wide</option>{departments.map((department) => <option value={idOf(department)} key={idOf(department)}>{firstString(department, ["name"], "Department")}</option>)}</select></label><button disabled={submitting} className={`${primaryButtonClass} self-end`} type="submit">{submitting ? <LoaderCircle className="size-4 animate-spin" /> : <MailPlus className="size-4" />}Invite member</button>{message && <p role="status" className={`text-xs sm:col-span-2 xl:col-span-5 ${message.includes("created") || message.includes("updated") ? "text-emerald-700" : "text-rose-700"}`}>{message}</p>}</form></SectionCard>
    <SectionCard title="Organization members" description={`${users.length} active or invited membership records.`}>{users.length === 0 ? <EmptyState icon={Users} title="No members are visible" description="Invite a member to create the first managed organization membership." /> : <div className="divide-y divide-[#edf0ee]">{users.map((user, index) => { const userId = firstString(user, ["user_id"], ""); const profile = recordValue(user, ["profiles"]); const status = firstString(user, ["status"], "active"); return <form onSubmit={(event) => void update(event, userId)} key={userId || index} className="grid gap-3 p-5 lg:grid-cols-[minmax(220px,1fr)_170px_180px_140px_auto] lg:items-end"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#e9f2ed] text-[#0d684d]"><UserCog className="size-4" /></span><div className="min-w-0"><p className="truncate text-xs font-semibold">{firstString(profile, ["full_name"], "Member")}</p><p className="mt-1 truncate text-[10px] text-[#7e8984]">User {userId.slice(0, 8) || "pending"} · Joined {formatDate(user.created_at)}</p></div></div><label className="text-[10px] font-bold uppercase tracking-[0.08em] text-[#7e8984]">Role<select name="role" defaultValue={firstString(user, ["role"], "department_user")} className="mt-1.5 h-9 w-full rounded-lg border bg-white px-2 text-xs font-normal normal-case tracking-normal"><option value="administrator">Administrator</option><option value="policy_manager">Policy manager</option><option value="department_user">Department user</option><option value="auditor">Auditor</option></select></label><label className="text-[10px] font-bold uppercase tracking-[0.08em] text-[#7e8984]">Department<select name="departmentId" defaultValue={firstString(user, ["department_id"], "")} className="mt-1.5 h-9 w-full rounded-lg border bg-white px-2 text-xs font-normal normal-case tracking-normal"><option value="">Organization-wide</option>{departments.map((department) => <option value={idOf(department)} key={idOf(department)}>{firstString(department, ["name"], "Department")}</option>)}</select></label><label className="text-[10px] font-bold uppercase tracking-[0.08em] text-[#7e8984]">Status<select name="status" defaultValue={status} className="mt-1.5 h-9 w-full rounded-lg border bg-white px-2 text-xs font-normal normal-case tracking-normal"><option value="active">Active</option><option value="invited">Invited</option><option value="suspended">Suspended</option></select></label><button type="submit" disabled={!userId} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border bg-white px-3 text-[11px] font-semibold hover:bg-[#fafbf9]"><Save className="size-3.5" />Save</button><div className="lg:hidden"><Badge tone={statusTone(status)}>{status}</Badge></div></form>; })}</div>}</SectionCard></div>;
}

export function DepartmentManagement() {
  const { data, loading, error, refresh } = useApi("/api/v1/departments"); const departments = arrayValue<ApiRecord>(data, ["departments"]);
  const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setMessage(""); const form = new FormData(event.currentTarget); try { await apiRequest("/api/v1/departments", { method: "POST", body: JSON.stringify({ name: String(form.get("name")), code: String(form.get("code")), description: String(form.get("description") ?? "") }) }); setMessage("Department created."); event.currentTarget.reset(); refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not create department."); } finally { setSubmitting(false); } }
  async function update(event: React.FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); const form = new FormData(event.currentTarget); setMessage(""); try { await apiRequest(`/api/v1/departments/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify({ name: String(form.get("name")), code: String(form.get("code")) }) }); setMessage("Department updated."); refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not update department."); } }
  if (loading && !data) return <SectionCard><LoadingState label="Loading departments…" rows={6} /></SectionCard>;
  if (error && !data) return <SectionCard><ErrorState message={error} onRetry={refresh} /></SectionCard>;
  return <div className="space-y-6"><SectionCard title="Add a department" description="Departments scope policy visibility, retrieval, findings, and action ownership."><form onSubmit={create} className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-[1fr_180px_1.4fr_auto] sm:p-6"><label className="text-xs font-semibold text-[#415049]">Name<input name="name" required className={fieldClass} placeholder="Examinations" /></label><label className="text-xs font-semibold text-[#415049]">Code<input name="code" required className={fieldClass} placeholder="EXAM" /></label><label className="text-xs font-semibold text-[#415049]">Description<input name="description" className={fieldClass} placeholder="Examination office and academic assessment" /></label><button disabled={submitting} className={`${primaryButtonClass} self-end`}>{submitting ? <LoaderCircle className="size-4 animate-spin" /> : <Building2 className="size-4" />}Add department</button>{message && <p role="status" className={`text-xs sm:col-span-2 lg:col-span-4 ${message.includes("created") || message.includes("updated") ? "text-emerald-700" : "text-rose-700"}`}>{message}</p>}</form></SectionCard><SectionCard title="Departments" description={`${departments.length} organization departments.`}>{departments.length === 0 ? <EmptyState icon={Building2} title="No departments configured" description="Add departments to scope document access, retrieval, findings, and action ownership." /> : <div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3 sm:p-6">{departments.map((department, index) => { const departmentId = idOf(department); const status = department.is_active === false ? "inactive" : "active"; return <form onSubmit={(event) => void update(event, departmentId)} key={departmentId || index} className="rounded-xl border bg-[#fafbf9] p-4"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-white text-[#0d684d] ring-1 ring-[#dfe5e1]"><Building2 className="size-4" /></span><Badge tone={statusTone(status)}>{status}</Badge></div><label className="mt-4 block text-[10px] font-bold uppercase tracking-[0.08em] text-[#7e8984]">Name<input name="name" defaultValue={firstString(department, ["name"], "")} className="mt-1.5 h-9 w-full rounded-lg border bg-white px-3 text-xs font-normal normal-case tracking-normal" /></label><label className="mt-3 block text-[10px] font-bold uppercase tracking-[0.08em] text-[#7e8984]">Code<input name="code" defaultValue={firstString(department, ["code"], "")} className="mt-1.5 h-9 w-full rounded-lg border bg-white px-3 text-xs font-normal normal-case tracking-normal" /></label><button className="mt-4 inline-flex h-9 w-full items-center justify-center gap-2 rounded-lg border bg-white text-[11px] font-semibold hover:bg-[#f5f7f5]"><Save className="size-3.5" />Save department</button></form>; })}</div>}</SectionCard></div>;
}

export function SettingsPanel() {
  const { data, loading, error, refresh } = useApi("/api/v1/settings");
  const rows = arrayValue<ApiRecord>(data, ["settings"]);
  const values = Object.fromEntries(rows.map((row) => [firstString(row, ["key"], ""), row.value]));
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const payload = { chunkSize: Number(form.get("chunkSize")), chunkOverlap: Number(form.get("chunkOverlap")), qualityThreshold: Number(form.get("qualityThreshold")), maxAutomaticRevisions: Number(form.get("maxAutomaticRevisions")), defaultRetrievalLimit: Number(form.get("defaultRetrievalLimit")) }; try { await apiRequest("/api/v1/settings", { method: "PATCH", body: JSON.stringify(payload) }); setMessage("Settings saved and audited."); refresh(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Could not save settings."); } finally { setSaving(false); } }
  if (loading && !data) return <SectionCard><LoadingState label="Loading organization settings…" rows={7} /></SectionCard>;
  if (error && !data) return <SectionCard><ErrorState message={error} onRetry={refresh} /></SectionCard>;
  return <form onSubmit={save} className="space-y-6"><SectionCard title="Ingestion and retrieval" description="Tune organization-level document chunking and the default number of reranked retrieval results."><div className="grid gap-4 p-5 sm:grid-cols-3 sm:p-6"><label className="text-xs font-semibold text-[#415049]">Chunk size (tokens)<input name="chunkSize" type="number" min="200" max="2000" defaultValue={Number(values["ingestion.chunk_size"] ?? 800)} className={fieldClass} required /></label><label className="text-xs font-semibold text-[#415049]">Chunk overlap (tokens)<input name="chunkOverlap" type="number" min="0" max="500" defaultValue={Number(values["ingestion.chunk_overlap"] ?? 120)} className={fieldClass} required /></label><label className="text-xs font-semibold text-[#415049]">Default retrieval limit<input name="defaultRetrievalLimit" type="number" min="3" max="50" defaultValue={Number(values["retrieval.default_limit"] ?? 12)} className={fieldClass} required /></label></div></SectionCard><SectionCard title="Quality review" description="Control the automatic revision boundary before a workflow proceeds to human review or reporting."><div className="grid gap-4 p-5 sm:grid-cols-2 sm:p-6"><label className="text-xs font-semibold text-[#415049]">Quality threshold<input name="qualityThreshold" type="number" min="0.5" max="1" step="0.01" defaultValue={Number(values["workflow.quality_threshold"] ?? 0.8)} className={fieldClass} required /></label><label className="text-xs font-semibold text-[#415049]">Maximum automatic revisions<input name="maxAutomaticRevisions" type="number" min="0" max="5" defaultValue={Number(values["workflow.max_automatic_revisions"] ?? 2)} className={fieldClass} required /></label></div></SectionCard><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900">Model names and secret credentials are controlled through server-side environment configuration and are never editable or displayed here. High and critical risk approval remains mandatory.</div>{message && <div role="status" className={`flex items-center gap-2 rounded-xl border p-4 text-xs ${message.includes("saved") ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-rose-200 bg-rose-50 text-rose-800"}`}>{message.includes("saved") ? <Check className="size-4" /> : <TriangleAlert className="size-4" />}{message}</div>}<button disabled={saving} className={`${primaryButtonClass} min-w-40`}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : <Settings2 className="size-4" />}{saving ? "Saving..." : "Save settings"}</button></form>;
}
